spring.datasource.url=jdbc:mysql://localhost:3306/studysync
spring.datasource.username=root
spring.datasource.password=pluto1307@

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080

# Allow circular references
spring.main.allow-circular-references=true

# Disable JWT filter
jwt.filter.enabled=false
